project:
  type: website
  output-dir: _site
  resources:
    - "*.pdf"
    - "*.html"
    - style/tx-patterns.css
  preview:
    port: 8000
    browser: true

execute:
  freeze: auto

website:
  title: "Jim Tyhurst, PhD"
  description: "Jim Tyhurst's website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - resume.qmd
      - blog.qmd
      - papers.qmd
    background: primary
  search: true
  twitter-card:
    card-style: summary
    creator: "@jimtyhurst"
    site: "@jimtyhurst"

format:
  html:
    theme:
      light: litera
      dark: darkly
    css:
      - styles.css
    toc: true
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
