---
title: "Resume"
---

Machine Learning Engineer ([PDF resume](./resources/Jim_Tyhurst-Resume-ML_Engineer.pdf))

## Expertise

I am an experienced ML Engineer with a Ph.D. in Linguistics, working in:

- machine learning
- data engineering
- feature engineering
- statistical analysis
- natural language processing
- software engineering
- enterprise application architecture

## Getting applications to production

My past enterprise architect experience is proving useful to productize new machine
learning applications that have been prototyped by data scientists.
My understanding of alternative architectures leads to well-structured maintainable code,
based on design patterns when appropriate and supported by automated unit tests.

I have delivered:

- AI applications
- Data pipelines
- ML models
- Enterprise application code with unit tests and integration tests
- Web services
- Instruction and mentoring in development processes
- Requirements specifications, including stories, use cases, and UML models
- Executable Architecture: Framework classes and application infrastructure


## Previous roles

- Machine Learning Engineer
- Data Engineer
- Software Engineer
- Application Architect
- Enterprise Architect
- R Developer
- Enterprise Java developer
- Instructor

## Technologies

- Machine learning
- Artificial Intelligence techniques
- Rule-based systems
- Object-oriented design
- Functional languages
- Relational databases
- NoSQL databases

## Education

- PhD in Linguistics
- MA in Linguistics
- BS in Computer Science
- BA in Mathematics

### Ph.D. in [Linguistics](https://linguistics.ucla.edu/ph-d-recipients/)
Dissertation: "[Logical Forms for English Sentences](./papers/1990-Logical-Forms-for-English-Sentences/)"<br>
University of California, Los Angeles ([UCLA](https://linguistics.ucla.edu/ph-d-recipients/))

My dissertation investigated the relationship between syntactic structure and
semantic interpretation, in order to develop an explicit model of the mapping
from surface syntactic forms to a level of Logical Form (LF) and finally to
truth values.

Honors: [W.M. Keck Research Award](https://www.wmkeck.org/research-overview/)
for "Semantic Representations for English" project on the Connection Machine.

### M.A. [Linguistics](https://linguistics.ucla.edu/)
Thesis: "[Tone in Kenyang Noun Phrases](./papers/1985-06-02-Tone-in-Kenyang-NPs/)"<br>
University of California, Los Angeles ([UCLA](https://linguistics.ucla.edu/))

My M.A. thesis provides an autosegmental description of tone in Kenyang, in
which noun roots carry tone melodies of three tone segments. The association
of tones to tone-bearing units occurs by general convention, accounting for
the difference in distribution of surface tone patterns on two and three
syllable nouns.

### B.S. [Computer Science](https://www.cs.uci.edu/)
University of California, Irvine ([UCI](https://www.uci.edu/))<br>

### B.A. [Mathematics](https://www.math.uci.edu/)
University of California, Irvine ([UCI](https://www.uci.edu/))<br>

Honors: Graduated _Cum Laude_ in both bachelor's degrees.

## Lifelong learning

[Preparing for Google Cloud Architect Professional Certificate](https://www.coursera.org/professional-certificates/gcp-cloud-architect#courses).
2021-11-28.
[Google 7-Course Specialization](https://www.coursera.org/professional-certificates/gcp-cloud-architect).
[Coursera](https://www.coursera.org/).

[Machine Learning with TensorFlow on Google Cloud](https://www.coursera.org/specializations/machine-learning-tensorflow-gcp#courses).
2018-12-18.
[Google 5-Course Specialization](https://www.coursera.org/specializations/machine-learning-tensorflow-gcp).
[Coursera](https://www.coursera.org/).

[Building R Packages](https://www.coursera.org/learn/r-packages).
2018-04-28.
[Johns Hopkins University](https://www.coursera.org/jhu).
[Coursera](https://www.coursera.org/).

[Introduction à la statistique avec R](https://lms.fun-mooc.fr/courses/UPSUD/42001S06/session06/ed827b15762542189af573ef096521f3/).
2016-11-24.
[Université Paris-Sud](https://www.fun-mooc.fr/fr/etablissements/universite-paris-saclay/).
[FUN MOOC](https://www.fun-mooc.fr/fr/cours/?limit=21&offset=0&query=statistique).

[Web sémantique et Web de données](https://lms.fun-mooc.fr/courses/inria/41002S02/session02/26a7ae9651d745fc998d2ec72ae37535/).
2016-05-26.
[Inria](https://www.fun-mooc.fr/fr/etablissements/inria/).
[FUN MOOC](https://www.fun-mooc.fr/fr/cours/?limit=21&offset=0&query=statistique).

Several [Data Science and R courses](https://www.coursera.org/specializations/jhu-data-science#courses).
2014.
[Johns Hopkins University](https://www.coursera.org/specializations/jhu-data-science).
[Coursera](https://www.coursera.org/).
